
root: /

Home: /
Archives: /archives
About: /about

language: en

author: stuart prine
description:

disqus:
  enable: false
  shortname:

google_site_verification:
google_analytics:

node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false
